/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;


public class bill extends javax.swing.JFrame {

    /**
     * Creates new form M_bill
     */
    public bill() {
    	getContentPane().setEnabled(false);
    	setForeground(new Color(204, 255, 255));
    	setBackground(new Color(204, 255, 255));
    	getContentPane().setBackground(new Color(204, 255, 255));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane1.setBackground(new Color(128, 128, 128));
        Bpayment_typ = new javax.swing.JTextField();
        Bstatus = new javax.swing.JTextField();
        jLabel_Bg_id = new javax.swing.JLabel();
        jLabel_Breception_num = new javax.swing.JLabel();
        jLabel_Bill_id = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_bill = new javax.swing.JTable();
        jLabel_Bpayment_typ = new javax.swing.JLabel();
        jLabel_Bstatus = new javax.swing.JLabel();
        jButton_view = new javax.swing.JButton();
        Bill_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new Color(192, 192, 192));
        jLabel1 = new javax.swing.JLabel();
        jButton_Insert = new javax.swing.JButton();
        jButton_Modify = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel_Btax = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Bpayment_typ.setColumns(2);

        Bstatus.setColumns(3);
      //  Bstatus.addActionListener(new java.awt.event.ActionListener() {
           // public void actionPerformed(java.awt.event.ActionEvent evt) {
                //amountActionPerformed(evt);
            //}
     //   });

        jLabel_Bg_id.setText("Guest ID");

        jLabel_Breception_num.setText("reception num");

        jLabel_Bill_id.setText("Bill_id");

        table_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill_id", "Bpayment_typ","Bstatus" ,"Btotal","Btax","Bexpect_pay_date","Breception_num","Rg_id"
            }
        ));
        table_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_billMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_bill);

        jLabel_Bpayment_typ.setText("Bpayment_typ");
        jLabel_Bpayment_typ.setToolTipText("");

        jLabel_Bstatus.setText("Bstatus");

        jButton_view.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_view.setText("View");
        jButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewActionPerformed(evt);
            }
        });

        Bill_id.setColumns(1);
       

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204),10 , true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jLabel1.setFont(new Font("Times New Roman", Font.BOLD, 28)); // NOI18N
        jLabel1.setForeground(new Color(0, 0, 0)); //bill table color
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill Table");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jButton_Insert.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_Insert.setText("Insert");
        jButton_Insert.setToolTipText("");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_Modify.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_Modify.setText("Modify");
        jButton_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifyActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        jButton_Back.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel_Btax.setText("Btax");

        jDesktopPane1.setLayer(Bpayment_typ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Bstatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Bg_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Breception_num, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Bill_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Bpayment_typ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Bstatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_view, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Bill_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_Insert, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_Modify, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_Delete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_Back, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Btax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        Btotal = new JTextField();
        Btotal.setColumns(4);
        
        JLabel jLabel_Btotal = new JLabel();
        jLabel_Btotal.setText("Btotal");
        
        Btax = new JTextField();
        Btax.setColumns(5);
        
        Breception_num = new JTextField();
        Breception_num.setColumns(7);
        
        Bg_id = new JTextField();
        Bg_id.setColumns(8);
        
        Bexpect_pay_date = new JTextField();
        Bexpect_pay_date.setColumns(6);
        
        jLabel_Bexpect_pay_date = new JLabel();
        jLabel_Bexpect_pay_date.setText("Bexpect_pay_date");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1Layout.setHorizontalGroup(
        	jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jDesktopPane1Layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(183)
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(230)
        					.addComponent(jButton_view, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addComponent(jLabel_Btotal, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(Btotal, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addComponent(jLabel_Bstatus)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(Bstatus, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addComponent(jLabel_Bill_id)
        							.addGap(26)
        							.addComponent(Bill_id, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addComponent(jLabel_Bpayment_typ)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(Bpayment_typ, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)))
        					.addGap(114)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(jLabel_Btax)
        						.addComponent(jLabel_Bg_id)
        						.addComponent(jLabel_Bexpect_pay_date, Alignment.LEADING)
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addGap(10)
        							.addComponent(jLabel_Breception_num, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(Bg_id, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Bexpect_pay_date, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Breception_num, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Btax, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 970, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jButton_Insert, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        						.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        							.addComponent(jButton_Back, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jButton_Delete, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jButton_Modify, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))))
        			.addGap(34))
        );
        jDesktopPane1Layout.setVerticalGroup(
        	jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jDesktopPane1Layout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel_Bill_id)
        								.addComponent(Bill_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(Bpayment_typ, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel_Bpayment_typ))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(Bstatus, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel_Bstatus))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(Btotal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel_Btotal)))
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(Bg_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel_Bg_id))
        							.addGap(6)
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(Bexpect_pay_date, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel_Bexpect_pay_date))
        							.addGap(6)
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(Breception_num, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel_Breception_num))
        							.addGap(6)
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(Btax, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel_Btax)))))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(jButton_view)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton_Insert)
        					.addGap(18)
        					.addComponent(jButton_Modify)))
        			.addGap(19)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addComponent(jButton_Delete)
        					.addGap(17)
        					.addComponent(jButton_Back)))
        			.addGap(25))
        );
        jDesktopPane1.setLayout(jDesktopPane1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   // private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
   // }//GEN-LAST:event_amountActionPerformed

    private void table_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_billMouseClicked
        // TODO add your handling code here:
        DefaultTableModel recordTable = (DefaultTableModel) table_bill.getModel();
        int selectedRows = table_bill.getSelectedRow();
        
        Bill_id.setText(recordTable.getValueAt(selectedRows, 0).toString());
        Bpayment_typ.setText(recordTable.getValueAt(selectedRows, 1).toString());
        Bstatus.setText(recordTable.getValueAt(selectedRows, 2).toString());
        Btotal.setText(recordTable.getValueAt(selectedRows, 3).toString());
        Btax.setText(recordTable.getValueAt(selectedRows, 4).toString());
        Bexpect_pay_date.setText(recordTable.getValueAt(selectedRows, 5).toString());
        Breception_num.setText(recordTable.getValueAt(selectedRows, 6).toString());
        Bg_id.setText(recordTable.getValueAt(selectedRows, 7).toString());

    }//GEN-LAST:event_table_billMouseClicked

    private void jButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        java.sql.ResultSet rs;

        String table = "SELECT * FROM bill";
        
        try{
            st = MyConnection.getConnection().prepareStatement(table) ;
            rs = st.executeQuery();
            
            while(rs.next()){
            	String vbillid = String.valueOf(rs.getInt("Bill_id"));
                String vbpaymenttyp = rs.getString("Bpayment_typ");
                String vBstatus = rs.getString("Bstatus");
                String vBtotal = rs.getString("Btotal");
                String vBtax = rs.getString("Btax");
                String vbexpectpaydate = rs.getString("Bexpect_pay_date");
                String vBreception_numnum = rs.getString("Breception_num");
                String vbgid = rs.getString("Bg_id");
                String Table_bill[] = {vbillid ,vbpaymenttyp ,vBstatus ,vBtotal ,vBtax ,vbexpectpaydate,vBreception_numnum,vbgid};
                DefaultTableModel tbmodel = (DefaultTableModel) table_bill.getModel();
                tbmodel.addRow(Table_bill);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_viewActionPerformed

   // private void bidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidActionPerformed
        // TODO add your handling code here:
   // }//GEN-LAST:event_bidActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        java.sql.ResultSet rs;

        String insert_Query = "INSERT INTO `hms`.`bill` (`Bill_id`, `Bpayment_typ`, `Bstatus`, `Btotal`, `Btax` , `Bexpect_pay_date` , `Breception_num`, `Bg_id`) VALUES (?, ?, ?, ?, ? ,?,?,?);";
        try {
            st = MyConnection.getConnection().prepareStatement(insert_Query) ;

            st.setString(1, Bill_id.getText());
            st.setString(2, Bpayment_typ.getText());
            st.setString(3, Bstatus.getText());
            st.setString(4, Btotal.getText());
            st.setString(5, Btax.getText());
            st.setString(6, Bexpect_pay_date.getText());
            st.setString(7, Breception_num.getText());
            st.setString(8, Bg_id.getText());

            int k = st.executeUpdate();
            if(k==1)
            JOptionPane.showMessageDialog(rootPane, "Record Added", "Succesful", 2);
            updateDB();
        } catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifyActionPerformed
        PreparedStatement st; 
        DefaultTableModel recordTable = (DefaultTableModel) table_bill.getModel();

        
       try {
           if(table_bill.getSelectedRowCount()==1){
        	   
            String billid = Bill_id.getText();
            String bpaymenttyp = Bpayment_typ.getText();
            String bstatus = Bstatus.getText();
            String btotal = Btotal.getText();
            String btax = Btax.getText();
            String bexpectpaydate = Bexpect_pay_date.getText();
            String Breception_numnum = Breception_num.getText();
            String bgid = Bg_id.getText();
            
            recordTable.setValueAt(billid, table_bill.getSelectedRow(), 0);
            recordTable.setValueAt(bpaymenttyp, table_bill.getSelectedRow(), 1);
            recordTable.setValueAt(bstatus, table_bill.getSelectedRow(), 2);
            recordTable.setValueAt(btotal, table_bill.getSelectedRow(), 3);
            recordTable.setValueAt(btax, table_bill.getSelectedRow(), 4);
            recordTable.setValueAt(bexpectpaydate, table_bill.getSelectedRow(), 5);
            recordTable.setValueAt(Breception_numnum, table_bill.getSelectedRow(), 6);
            recordTable.setValueAt(bgid, table_bill.getSelectedRow(), 7);
            
            String update_Query = "UPDATE `hms`.`bill` SET `Bpayment_typ` = '"+bpaymenttyp+"', `Bstatus` = '"+bstatus+"', `Btotal` = '"+btotal+"', `Btax` = '"+btax+"', `Bexpect_pay_date` = '"+bexpectpaydate+"', `Breception_num` = '"+Breception_numnum+"', `Bg_id` = '"+bgid+"'   WHERE `Bill_id` = '"+billid+"';";
            st = MyConnection.getConnection().prepareStatement(update_Query) ;
            st.execute();
            JOptionPane.showMessageDialog(rootPane, "Modified Succesfully");
      }else{
             if(table_bill.getRowCount()==0){
                 JOptionPane.showMessageDialog(rootPane, "tableis empty");
             }else{
                 JOptionPane.showMessageDialog(rootPane, "Please select single row to modify");
             }
         }
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
       
        
        
      
    }//GEN-LAST:event_jButton_modifyActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel recordTable = (DefaultTableModel) table_bill.getModel();
        int selectedRows = table_bill.getSelectedRow();
        PreparedStatement st;
        java.sql.ResultSet rs;

        String insert_Query = "DELETE FROM `hms`.`bill` WHERE Bill_id=?";
        try {
           int  nid = Integer.parseInt(recordTable.getValueAt(selectedRows, 0).toString());

            int deleteditem = JOptionPane.showConfirmDialog(rootPane, "Confirm if you want to delete record","Warning",JOptionPane.YES_NO_OPTION);
            if(deleteditem == JOptionPane.YES_OPTION){

                st = MyConnection.getConnection().prepareStatement(insert_Query) ;

                st.setInt(1, nid);
                st.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Record Deleted", "Succesful", 2);
                updateDB();
                Bill_id.setText("");
                Bill_id.requestFocus();
                Bpayment_typ.setText("");
                Bstatus.setText("");
                Btotal.setText("");
                Btax.setText("");
                Bexpect_pay_date.setText("");
                Breception_num.setText("");
                Bg_id.setText("");
                
            }
        }catch(HeadlessException | NumberFormatException | SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.hide();
        HomePageM f = new HomePageM();
        f.setVisible(true);
        f.pack();
            f.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed
   
    public void updateDB(){
        PreparedStatement st;
        java.sql.ResultSet rs;
        
        String update_Query = "SELECT * FROM bill";
        try {
            st = MyConnection.getConnection().prepareStatement(update_Query) ;
            rs = st.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
        
            int q = stData.getColumnCount();
        
            DefaultTableModel recordTable = (DefaultTableModel) table_bill.getModel();
            recordTable.setRowCount(0);
        
            while(rs.next()){
            	Vector CoulmnData = new Vector();
            
            	for (int i = 0 ; i <= q ;i++){
            		CoulmnData.add(rs.getString("Bill_id"));
            		CoulmnData.add(rs.getString("Bpayment_typ"));
            		CoulmnData.add(rs.getString("Bstatus"));
            		CoulmnData.add(rs.getString("Btotal"));
            		CoulmnData.add(rs.getString("Btax"));
            		CoulmnData.add(rs.getString("Bexpect_pay_date"));
            		CoulmnData.add(rs.getString("Breception_num"));
            		CoulmnData.add(rs.getString("Bg_id"));       
                }
            	recordTable.addRow(CoulmnData);
            }
        
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bstatus;
    private javax.swing.JTextField Bill_id;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JButton jButton_Modify;
    private javax.swing.JButton jButton_view;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Bill_id;
    private javax.swing.JLabel jLabel_Bpayment_typ;
    private javax.swing.JLabel jLabel_Bstatus;
    private javax.swing.JLabel jLabel_Bg_id;
    private javax.swing.JLabel jLabel_Breception_num;
    private javax.swing.JLabel jLabel_Btax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField Bpayment_typ;
    private javax.swing.JTable table_bill;
    private JTextField Btotal;
    private JTextField Btax;
    private JTextField Breception_num;
    private JTextField Bg_id;
    private JTextField Bexpect_pay_date;
    private JLabel jLabel_Bexpect_pay_date;
}
