/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.SystemColor;


public class M_Employee extends javax.swing.JFrame {

    /**
     * Creates new form M_Employee
     */
    public M_Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane1.setForeground(SystemColor.activeCaption);
        jDesktopPane1.setBackground(SystemColor.controlHighlight);
        Eaddrress = new javax.swing.JTextField();
        Ereception_num = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ephone_num = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Efname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_employee = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_view = new javax.swing.JButton();
        Eid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_add = new javax.swing.JButton();
        jButton_modify = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Elname = new javax.swing.JTextField();
        Elname.setColumns(3);
        jLabel8 = new javax.swing.JLabel();
        Erole = new javax.swing.JTextField();
        Erole.setColumns(7);
        jLabel9 = new javax.swing.JLabel();
        Super_id = new javax.swing.JTextField();
        Super_id.setColumns(8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Eaddrress.setColumns(5);

        Ereception_num.setColumns(9);
        Ereception_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ereception_numActionPerformed(evt);
            }
        });

        jLabel5.setText("Ephone_num");

        Ephone_num.setColumns(6);

        jLabel6.setText("Efname");

        Efname.setColumns(2);

        jLabel2.setText("Eid");

        table_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eid", "Efname", "Elname","Esalary","Eaddress", "Ephone_num",  "Erole", "super_ID","Ereception_num"
            }
        ));
        table_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_employeeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_employee);

        jLabel3.setText("Eaddress");
        jLabel3.setToolTipText("");

        jLabel4.setText("Ereception_num");

        jButton_view.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_view.setText("View");
        jButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewActionPerformed(evt);
            }
        });

        Eid.setColumns(1);
        Eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(SystemColor.desktop);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Table");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jButton_add.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_add.setText("Insert");
        jButton_add.setToolTipText("");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_modify.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton_modify.setText("Modify");
        jButton_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifyActionPerformed(evt);
            }
        });

        bt_delete.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Elname");

        jLabel8.setText("Erole");

        jLabel9.setText("super_ID");

        jDesktopPane1.setLayer(Eaddrress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Ereception_num, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Ephone_num, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Efname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_view, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Eid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_add, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_modify, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_delete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Elname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Erole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Super_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        Esalary = new JTextField();
        Esalary.setColumns(4);
        
        JLabel lblESalary = new JLabel();
        lblESalary.setText("E salary");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1Layout.setHorizontalGroup(
        	jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jDesktopPane1Layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(80)
        					.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 827, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(183)
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel2)
        								.addComponent(jLabel8)
        								.addComponent(jLabel3))
        							.addGap(26))
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel4)
        								.addComponent(lblESalary, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)))
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(Eid, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        							.addComponent(Eaddrress, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        							.addComponent(Ereception_num, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
        						.addComponent(Erole, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Esalary, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
        					.addGap(110)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel5)
        						.addComponent(jLabel7)
        						.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        							.addComponent(jLabel6)
        							.addComponent(jLabel9)))
        					.addGap(31)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(Ephone_num)
        						.addComponent(Efname, GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        						.addComponent(Elname)
        						.addComponent(Super_id))))
        			.addGap(94)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jButton4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton_add, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton_view, GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        				.addComponent(jButton_modify, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(bt_delete, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(76))
        );
        jDesktopPane1Layout.setVerticalGroup(
        	jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jDesktopPane1Layout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(Eid, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5)
        				.addComponent(Ephone_num, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(Eaddrress, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6)
        				.addComponent(Efname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addGap(18)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(Elname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Ereception_num, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addGap(23)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel8)
        				.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(Erole, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel9)
        					.addComponent(Super_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(17)
        					.addComponent(jButton_view)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton_add)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton_modify)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(bt_delete)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton4))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(Esalary, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblESalary))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE)))
        			.addGap(72))
        );
        jDesktopPane1.setLayout(jDesktopPane1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ereception_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ereception_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ereception_numActionPerformed

    private void table_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_employeeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel recordTable = (DefaultTableModel) table_employee.getModel();
        int selectedRows = table_employee.getSelectedRow();

        Eid.setText(recordTable.getValueAt(selectedRows, 0).toString());
        Efname.setText(recordTable.getValueAt(selectedRows, 1).toString());
        Elname.setText(recordTable.getValueAt(selectedRows,2).toString());
        Esalary.setText(recordTable.getValueAt(selectedRows,3).toString());
        Eaddrress.setText(recordTable.getValueAt(selectedRows,4).toString());
        Ephone_num.setText(recordTable.getValueAt(selectedRows, 5).toString());
        Erole.setText(recordTable.getValueAt(selectedRows, 6).toString());
        Super_id.setText(recordTable.getValueAt(selectedRows, 7).toString());
        Ereception_num.setText(recordTable.getValueAt(selectedRows, 8).toString());
      
    }//GEN-LAST:event_table_employeeMouseClicked

    private void jButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        java.sql.ResultSet rs;
        //st = MyConnection.getConnection().;
        String table = "SELECT * FROM employee";
        try{
            st = MyConnection.getConnection().prepareStatement(table) ;
            rs = st.executeQuery();

            while(rs.next()){
                String id = String.valueOf(rs.getInt("Eid"));
                String fn = rs.getString("Efname");
                String ln = rs.getString("Elname");
                String es = rs.getString("Esalary");
                String add = rs.getString("Eaddress");
                String ph = rs.getString("Ephone_num");
                String et = rs.getString("Erole");
                String sd = rs.getString("super_ID");
                String g = rs.getString("Ereception_num");
                String Table_employee[] = {id ,fn ,ln ,es ,add,ph,et,sd,g};
                DefaultTableModel tbmodel = (DefaultTableModel) table_employee.getModel();

                tbmodel.addRow(Table_employee);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_viewActionPerformed

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        java.sql.ResultSet rs;

        String insert_Query = "INSERT INTO `hms`.`employee` (`Eid`,`Efname`, `Elname`, `Esalary`, `Eaddress`, `Ephone_num`, `Erole`, `Super_id`, `Ereception_num`) VALUES (?, ?, ?, ?, ?, ?, ?, ? , ?);";
        try {
            st = MyConnection.getConnection().prepareStatement(insert_Query) ;

            st.setString(1, Eid.getText());
            st.setString(2, Efname.getText());
            st.setString(3, Elname.getText());
            st.setString(4, Esalary.getText());
            st.setString(5, Eaddrress.getText());
            st.setString(6, Ephone_num.getText());
            st.setString(7, Erole.getText());
            st.setString(8, Super_id.getText());
            st.setString(9, Ereception_num.getText());

           int k = st.executeUpdate();
            if(k==1)
            JOptionPane.showMessageDialog(rootPane, "Record Added", "Succesful", 2);
            updateDB();
        } catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifyActionPerformed  
       PreparedStatement st;
        java.sql.ResultSet rs;
        DefaultTableModel recordTable = (DefaultTableModel) table_employee.getModel();
        //String insert_Query = "UPDATE `hms`.`employee` SET Eid=? ,`Eaddress` = ?, `Ereception_num` = ?, `Ephone_num` = ?, `Efname` = ?, `Elname` = ?, `Erole` =?, `super_ID` = ? WHERE (`Eid` = ?);";
        try {
            //st = MyConnection.getConnection().prepareStatement(insert_Query) ;
        if(table_employee.getSelectedRowCount()==1){
            String eid = Eid.getText();
            String fn = Efname.getText();
            String ln = Elname.getText();
            String es = Esalary.getText();
            String addr = Eaddrress.getText();
            String rec = Ereception_num.getText();
            String ph = Ephone_num.getText();
            String er = Erole.getText();
            String sd = Super_id.getText();
          
            
            recordTable.setValueAt(eid, table_employee.getSelectedRow(), 0);
            recordTable.setValueAt(fn, table_employee.getSelectedRow(), 1);
            recordTable.setValueAt(ln, table_employee.getSelectedRow(), 2);
            recordTable.setValueAt(es, table_employee.getSelectedRow(),3);
            recordTable.setValueAt(addr, table_employee.getSelectedRow(), 4);
            recordTable.setValueAt(ph, table_employee.getSelectedRow(),5);
            recordTable.setValueAt(er, table_employee.getSelectedRow(), 6);
            recordTable.setValueAt(sd, table_employee.getSelectedRow(), 7);
            recordTable.setValueAt(rec, table_employee.getSelectedRow(), 8);
            
            String update_Query = "UPDATE `hms`.`employee` SET `Efname` = '"+fn+"', `Elname` = '"+ln+"', `Esalary` = '"+es+"', `Eaddress` = '"+addr+"', `Ephone_num` = '"+ph+"', `Erole` = '"+er+"', `Ereception_num` = '"+rec+"' WHERE `Eid` = '"+eid+"'";
            st = MyConnection.getConnection().prepareStatement(update_Query) ;
            st.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Modified Succesfully");
        }else{
               if(table_employee.getRowCount()==0){
                   JOptionPane.showMessageDialog(rootPane, "tableis empty");
               }else{
                   JOptionPane.showMessageDialog(rootPane, "Please select single row to modify");
               }
        }
    }//GEN-LAST:event_jButton_modifyActionPerformed
    catch(HeadlessException | NumberFormatException | SQLException e){
            System.out.println(e);
        }}
    
    
    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel recordTable = (DefaultTableModel) table_employee.getModel();
        int selectedRows = table_employee.getSelectedRow();
        PreparedStatement st;
        java.sql.ResultSet rs;

        String insert_Query = "DELETE FROM `hms`.`employee` WHERE Eid=? ";
        try {
            int nid = Integer.parseInt(recordTable.getValueAt(selectedRows, 0).toString());

            int deleteditem = JOptionPane.showConfirmDialog(rootPane, "Confirm if you want to delete record","Warning",JOptionPane.YES_NO_OPTION);
            if(deleteditem == JOptionPane.YES_OPTION){

                st = MyConnection.getConnection().prepareStatement(insert_Query) ;

                st.setInt(1, nid);
                st.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Record Deleted", "Succesful", 2);
                updateDB();
                Eid.setText("");
                Eid.requestFocus();
                Esalary.setText("");
                Eaddrress.setText("");
                Ereception_num.setText("");
                Ephone_num.setText("");
                Efname.setText("");
                Elname.setText("");
                Erole.setText("");
                Super_id.setText("");

            }
        }catch(HeadlessException | NumberFormatException | SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.hide();
        HomePageM f = new HomePageM();
        f.setVisible(true);
        f.pack();
            f.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed
     public void updateDB(){
        PreparedStatement st;
        java.sql.ResultSet rs;
        Connection con;
        String update_Query = "SELECT * FROM employee";
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","123456");
        
         st = MyConnection.getConnection().prepareStatement(update_Query) ;
        rs = st.executeQuery();
        ResultSetMetaData stData = rs.getMetaData();
        
        int q = stData.getColumnCount();
        
        DefaultTableModel recordTable = (DefaultTableModel) table_employee.getModel();
        recordTable.setRowCount(0);
        
        while(rs.next()){
            Vector CoulmnData = new Vector();
            
            for (int i = 0 ; i <= q ;i++){
                CoulmnData.add(rs.getString("Eid"));
                CoulmnData.add(rs.getString("Efname"));
                CoulmnData.add(rs.getString("Elname"));
                CoulmnData.add(rs.getString("Esalary"));
                CoulmnData.add(rs.getString("Eaddress"));
                CoulmnData.add(rs.getString("Ephone_num"));
                CoulmnData.add(rs.getString("Erole"));
               
                CoulmnData.add(rs.getString("super_ID"));
                CoulmnData.add(rs.getString("Ereception_num"));    
                }
             recordTable.addRow(CoulmnData);
        }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Eaddrress;
    private javax.swing.JButton bt_delete;
    private javax.swing.JTextField Ephone_num;
    private javax.swing.JTextField Eid;
    private javax.swing.JTextField Erole;
    private javax.swing.JTextField Efname;
    private javax.swing.JTextField Ereception_num;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_modify;
    private javax.swing.JButton jButton_view;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField Elname;
    private javax.swing.JTextField Super_id;
    private javax.swing.JTable table_employee;
    private JTextField Esalary;
}
