import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class M_room extends javax.swing.JFrame {

 

    /**

     * Creates new form M_room

     */

    public M_room() {

        initComponents();

    }

 

    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {

 

        jDesktopPane1 = new javax.swing.JDesktopPane();

       status= new javax.swing.JTextField();//price status

        type1 = new javax.swing.JTextField(); //avl type1

        jLabel5 = new javax.swing.JLabel();

        gid = new javax.swing.JTextField(); //type gid

        jLabel2 = new javax.swing.JLabel();

        jScrollPane3 = new javax.swing.JScrollPane();

        table_room = new javax.swing.JTable();

        jLabel3 = new javax.swing.JLabel();

        jLabel4 = new javax.swing.JLabel();

        jButton_view = new javax.swing.JButton();

        rnum = new javax.swing.JTextField();

        jPanel1 = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();

        jButton_add = new javax.swing.JButton();

        jButton_modify = new javax.swing.JButton();

        bt_delete = new javax.swing.JButton();

        jButton4 = new javax.swing.JButton();

 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

 

        status.setColumns(2); //price status

 

        type1.setColumns(3); //avl type1

        type1.addActionListener(new java.awt.event.ActionListener() //avl type1

        {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                avlActionPerformed(evt);

            }

        });

 

        jLabel5.setText("Guest id");//////name

 

        gid.setColumns(4); //type gid

 

       jLabel2.setText("Room num");////name

 

        table_room.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {

 

            },

            new String [] { "Room_num", "Rstatus", "Rtype", "Rg_id" //taple GUI

               // "Room_num", "Price", "Availibilty", "Type"///////// taple

            }

        ));

        table_room.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                table_roomMouseClicked(evt);

            }

        });

        jScrollPane3.setViewportView(table_room);

 

        jLabel3.setText("Room status");////Name

        jLabel3.setToolTipText("");

 

        jLabel4.setText("Room type");////name

 

        jButton_view.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N

        jButton_view.setText("View");

        jButton_view.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton_viewActionPerformed(evt);

            }

        });

 

        rnum.setColumns(1);

        rnum.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                rnumActionPerformed(evt);

            }

        });

 

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

 

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Room Table");

 

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);

        jPanel1.setLayout(jPanel1Layout);

        jPanel1Layout.setHorizontalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

                .addContainerGap(201, Short.MAX_VALUE)

                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(188, 188, 188))

        );

        jPanel1Layout.setVerticalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

                .addContainerGap(22, Short.MAX_VALUE)

                .addComponent(jLabel1)

                .addGap(21, 21, 21))

        );

 

        jButton_add.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N

        jButton_add.setText("Insert");

        jButton_add.setToolTipText("");

        jButton_add.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton_addActionPerformed(evt);

            }

        });

 

        jButton_modify.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N

        jButton_modify.setText("Modify");

        jButton_modify.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton_modifyActionPerformed(evt);

            }

        });

 

        bt_delete.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N

        bt_delete.setText("Delete");

        bt_delete.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                bt_deleteActionPerformed(evt);

            }

        });

 

        jButton4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N

        jButton4.setText("Back");

        jButton4.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton4ActionPerformed(evt);

            }

        });

 

        jDesktopPane1.setLayer(status, javax.swing.JLayeredPane.DEFAULT_LAYER);//price status

        jDesktopPane1.setLayer(type1, javax.swing.JLayeredPane.DEFAULT_LAYER);//avl type1

        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(gid, javax.swing.JLayeredPane.DEFAULT_LAYER);//type gid

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jButton_view, javax.swing.JLayeredPane.DEFAULT_LAYER);

       jDesktopPane1.setLayer(rnum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jButton_add, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jButton_modify, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(bt_delete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

 

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1Layout.setHorizontalGroup(
        	jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jDesktopPane1Layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(183)
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(12)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addComponent(jLabel3)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(status, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED))
        						.addGroup(jDesktopPane1Layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(rnum, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)))
        					.addGap(101)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel5)
        						.addComponent(jLabel4))
        					.addGap(35)
        					.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(type1, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        						.addComponent(gid, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(183, Short.MAX_VALUE))
        		.addGroup(jDesktopPane1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 747, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(bt_delete, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton_view, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton_add, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton_modify, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE))
        			.addGap(58))
        );
        jDesktopPane1Layout.setVerticalGroup(
        	jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jDesktopPane1Layout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(rnum, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5)
        				.addComponent(gid, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(status, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3)
        				.addComponent(type1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addGap(52)
        			.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton_view)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton_add)
        					.addGap(18)
        					.addComponent(jButton_modify)
        					.addGap(18)
        					.addComponent(bt_delete)
        					.addGap(18)
        					.addComponent(jButton4))
        				.addGroup(jDesktopPane1Layout.createSequentialGroup()
        					.addGap(33)
        					.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(14, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayout(jDesktopPane1Layout);

 

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jDesktopPane1)

        );

        layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jDesktopPane1)

        );

 

        pack();

    }// </editor-fold>//GEN-END:initComponents

 

    private void avlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avlActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_avlActionPerformed

 

    private void table_roomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_roomMouseClicked

        // TODO add your handling code here:

        DefaultTableModel recordTable = (DefaultTableModel) table_room.getModel();

        int selectedRows = table_room.getSelectedRow();

 

        rnum.setText(recordTable.getValueAt(selectedRows, 0).toString());

        status.setText(recordTable.getValueAt(selectedRows, 1).toString());//price status

        type1.setText(recordTable.getValueAt(selectedRows, 2).toString()); //avl type1

        gid.setText(recordTable.getValueAt(selectedRows, 3).toString());//type gid

 

    }//GEN-LAST:event_table_roomMouseClicked

 

    private void jButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewActionPerformed

        // TODO add your handling code here:

        PreparedStatement st;

        java.sql.ResultSet rs;

        //st = MyConnection.getConnection().;

        String table = "SELECT * FROM room";

        try{

            st = MyConnection.getConnection().prepareStatement(table) ;

            rs = st.executeQuery();

            //"Room_num", "Rstatus", "Rtype", "Rg_id"

            while(rs.next()){ //table

                String id = String.valueOf(rs.getInt("Room_num"));

                String fName = rs.getString("Rstatus");

                String lName = rs.getString("Rtype");

                String phone = rs.getString("Rg_id");

                String Table_room[] = {id ,fName ,lName ,phone };

                DefaultTableModel tbmodel = (DefaultTableModel) table_room.getModel();

 

                tbmodel.addRow(Table_room);

            }

        }catch(Exception e){

            e.printStackTrace();

           System.out.println(e);

        }

    }//GEN-LAST:event_jButton_viewActionPerformed

 

    private void rnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnumActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_rnumActionPerformed

 

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed

        // TODO add your handling code here:

        PreparedStatement st;

        java.sql.ResultSet rs;

//  //"Room_num", "Rstatus", "Rtype", "Rg_id"

        String insert_Query = "INSERT INTO `hms`.`room` (`Room_num`, `Rstatus`, `Rtype`, `Rg_id`) VALUES (?, ?, ?, ?);"; ///table

        try {

            st = MyConnection.getConnection().prepareStatement(insert_Query) ;

 

            st.setString(1, rnum.getText());

            st.setString(2, status.getText());//price status

            st.setString(3, type1.getText()); //avl type1

            st.setString(4, gid.getText()); //type gid

           

            st.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Record Added", "Succesful", 2);

            updateDB();

        } catch(Exception e){

            System.out.println(e);

        }

 

    }//GEN-LAST:event_jButton_addActionPerformed

 

    private void jButton_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifyActionPerformed

        // TODO add your handling code here:

        PreparedStatement st;

        java.sql.ResultSet rs;

        DefaultTableModel recordTable = (DefaultTableModel) table_room.getModel();

        try{

        if(table_room.getSelectedRowCount()==1){

            String nid = rnum.getText();

            String name1 = status.getText();//price status

            String name2 = type1.getText();//avl type1

            String ph = gid.getText();// type gid

           

 

            recordTable.setValueAt(nid, table_room.getSelectedRow(), 0);

            recordTable.setValueAt(name1, table_room.getSelectedRow(), 1);

            recordTable.setValueAt(name2, table_room.getSelectedRow(), 2);

            recordTable.setValueAt(ph, table_room.getSelectedRow(), 3);

           

            String update_Query = "UPDATE `hms`.`room` SET `Rstatus` = '"+name1+"', `Rtype` = '"+name2+"', `Rg_id` = '"+ph+"' WHERE `Room_num` = '"+nid+"'";

            st = MyConnection.getConnection().prepareStatement(update_Query) ;

            st.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Successfully modified");

 

        }else{

            if(table_room.getRowCount()==0){

                JOptionPane.showMessageDialog(rootPane, "table is empty");

            }else{

                JOptionPane.showMessageDialog(rootPane, "Please select single row to modify");

            }

        }

        }catch(Exception e){

             System.out.println(e.getMessage());

         }

    }//GEN-LAST:event_jButton_modifyActionPerformed

 

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed

        // TODO add your handling code here:

        DefaultTableModel recordTable = (DefaultTableModel) table_room.getModel();

        int selectedRows = table_room.getSelectedRow();

        PreparedStatement st;

        java.sql.ResultSet rs;

 

        String insert_Query = "DELETE FROM `hms`.`room` WHERE Room_num=?"; //table //hotel_dbms hms

        try {

           int nid = Integer.parseInt(recordTable.getValueAt(selectedRows, 0).toString());

 

           int deleteditem = JOptionPane.showConfirmDialog(rootPane, "Confirm if you want to delete record","Warning",JOptionPane.YES_NO_OPTION);

            if(deleteditem == JOptionPane.YES_OPTION){

 

                st = MyConnection.getConnection().prepareStatement(insert_Query) ;

 

                st.setInt(1, nid);

                st.executeUpdate();

                JOptionPane.showMessageDialog(rootPane, "Record Deleted", "Succesful", 2);

                updateDB();

                rnum.setText("");

                rnum.requestFocus();//

                status.setText("");//price status

                type1.setText("");//avl type1

                gid.setText("");//type gid

               

 

            }

        }catch(HeadlessException | NumberFormatException | SQLException e){

            System.out.println(e);

        }

    }//GEN-LAST:event_bt_deleteActionPerformed

 

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:

        this.hide();

        WelcomePage wp = new WelcomePage();

        wp.setVisible(true);

        wp.pack();

           wp.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton4ActionPerformed

public void updateDB(){

        PreparedStatement st;

        java.sql.ResultSet rs;

       

        String update_Query = "SELECT * FROM room";

        try {

            st = MyConnection.getConnection().prepareStatement(update_Query) ;

        rs = st.executeQuery();

        ResultSetMetaData stData = rs.getMetaData();

       

        int q = stData.getColumnCount();

       

        DefaultTableModel recordTable = (DefaultTableModel) table_room.getModel();

        recordTable.setRowCount(0);

       

        while(rs.next()){

            Vector CoulmnData = new Vector();

          //"Room_num", "Rstatus", "Rtype", "Rg_id"

            for (int i = 0 ; i <= q ;i++){////// Taple

                CoulmnData.add(rs.getString("Room_num"));//Room_num Room_num

                 CoulmnData.add(rs.getString("Rstatus"));//Price Rstatus

                  CoulmnData.add(rs.getString("Rtype"));//Availibilty Rtype

                   CoulmnData.add(rs.getString("Rg_id"));// Type Rg_id

                   

                   

                }

             recordTable.addRow(CoulmnData);

        }

        }catch(Exception e){

            System.out.println(e);

        }

    }

   

 

    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(M_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(M_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(M_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(M_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

 

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new M_room().setVisible(true);

            }

        });

    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JTextField type1; //avl type1

    private javax.swing.JButton bt_delete;

    private javax.swing.JButton jButton4;

    private javax.swing.JButton jButton_add;

    private javax.swing.JButton jButton_modify;

    private javax.swing.JButton jButton_view;

    private javax.swing.JDesktopPane jDesktopPane1;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JScrollPane jScrollPane3;

    private javax.swing.JTextField status; //price status

    private javax.swing.JTextField rnum;

    private javax.swing.JTable table_room;

    private javax.swing.JTextField gid;//type gid

    // End of variables declaration//GEN-END:variables

}